// Generated by https://quicktype.io

export interface HistoryResponse {
  country: string;
  timeline: Timeline;
}

export interface Timeline {
  cases: { [key: string]: number };
  deaths: { [key: string]: number };
  recovered: { [key: string]: number };
}
